[workspace]
authors = ["Jez Ng <me@jezng.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mpt"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062405,<26"
